### ISSUE TITLE
Device Unavailable

### ISSUE THREAD

**Issue by kerbysj** [tomasmcguinness/homeassistant-mixergy#11]
FOr the past week the tank has become unavailable, Ive tried reloading the device, rebooting HA, HAOS and the VM. 
This is the error.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mixergy/sensor.py", line 25, in async_update_data
    await tank.fetch_data()
  File "/config/custom_components/mixergy/tank.py", line 274, in fetch_data
    await self.fetch_last_measurement()
  File "/config/custom_components/mixergy/tank.py", line 261, in fetch_last_measurement
    tank_result = await resp.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 67, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain;charset=utf-8', url=URL('https://www.mixergy.io/api/v2/tanks/BLANKEDTHISASASSUMEITSMYID/settings')

**Comment by tomasmcguinness** [comment]
Hi. Are you running the latest version? I made some changes recently to add a new sensor, but it broke the integration because of how the API returns settings information. I've since correct this.

Would you mind checking the version you're running?

**Comment by kerbysj** [comment]
No you are completely right. I keep forgetting i installed this manually ages ago and tried to swap to HACS but it didnt take. 
Just removed the folder and added the new version and its working. So sorry to waste your time.

**Comment by tomasmcguinness** [comment]
Cool. I’ll close this issue!
