### ISSUE TITLE
All entities unavailable

### ISSUE THREAD

**Issue by XoneDB4** [tomasmcguinness/homeassistant-mixergy#16]
Hi, yesterday afternoon, all mixergy entities suddenly became unavailable and I can't seem to get them back. I know Mixergy did a big server update at the weekend; has anyone else had problems? I'm no developer so I'm struggling to get to the bottom of this - I turned on logging on the integration and this is what I got, not sure if helpful?

`Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:258
Integration: Sensor (documentation, issues)
First occurred: 10:41:43 (5 occurrences)
Last logged: 10:56:19

Error while setting up mixergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mixergy/sensor.py", line 25, in async_update_data
    await tank.fetch_data()
  File "/config/custom_components/mixergy/tank.py", line 277, in fetch_data
    await self.fetch_last_measurement()
  File "/config/custom_components/mixergy/tank.py", line 232, in fetch_last_measurement
    heat_source = current["heat_source"]
                  ~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'heat_source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mixergy/sensor.py", line 30, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'heat_source'
`

**Comment by tomasmcguinness** [comment]
I've just checked my Home Assistant and my integration is broken too!! 

I suspect they may have changed the API. I'll investigate and report back!

**Comment by DirkFace** [comment]
Mine went 'off' during their server maintenance period, but all came back ON & reporting data correctly in HA after. Sent from my iPhone. On 8 Aug 2023, at 14:56, Tomas McGuinness ***@***.***> wrote:﻿
I've just checked my Home Assistant and my integration is broken too!!
I suspect they may have changed the API. I'll investigate and report back!

**Comment by tomasmcguinness** [comment]
I haven’t had a chance to check this further. Are you still having an issue?

**Comment by XoneDB4** [comment]
Yeh, still got no entities.

**Comment by XoneDB4** [comment]
@tomasmcguinness I don't know if you changed anything but it all came back online yesterday!

**Comment by tomasmcguinness** [comment]
Not a clue! The issue was in the current state JSON, but it seems to have worked itself out :)
