### ISSUE TITLE
Integration Setup failure

### ISSUE THREAD

**Issue by MartinCRichards** [tomasmcguinness/homeassistant-mixergy#53]
Each time I try to set up the integration I get an error :-(

I've used the Python Script you supplied elsewhere to confirm the login details and serial number match, but the log files show the error below:

```
2024-04-07 00:54:56.130 ERROR (MainThread) [custom_components.mixergy.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mixergy/config_flow.py", line 82, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mixergy/config_flow.py", line 49, in validate_input
    result = await tank.test_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mixergy/tank.py", line 62, in test_connection
    return await self.fetch_tank_information()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mixergy/tank.py", line 346, in fetch_tank_information
    self._has_pv_diverter = (tank_configuration["mixergyPvType"] != "NO_INVERTER")
                             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'mixergyPvType'
```

Guess the next step is to dump the returned configuration and see what's in there?

**Comment by MartinCRichards** [comment]
Had a quick play in Postman and I think this is the problem:

```
    "tankModelCode": "MX-180-IDE-EXT-580-1-1-B-0",
    "configuration": "{\"tankType\":\"NORMAL\"}",
    "volume": 180,

```
My tank doesn't return a mixergyPvType, only a tankType.  I've just set the value False in tank.py and all seems to be ok now!

**Comment by tomasmcguinness** [comment]
Sorry about that Martin! 

The API is a bit of a pain - I'll look at getting a fix in ASAP.

**Comment by MartinCRichards** [comment]
Nice one,  thank you!
